### ISSUE TITLE
Dependency not found

### ISSUE THREAD

**Issue by fabio-paiva-sp** [kokspflanze/ZfcTicketSystem#1]
PServerCMS is missing

PHP Fatal error:  Uncaught exception 'Doctrine\ORM\Mapping\MappingException' with message 'The target-entity PServerCMS\Entity\Users cannot be found in 'ZfcTicketSystem\Entity\Ticketsubject#user'.' in /home/fabio/NetBeansProjects/aso/vendor/doctrine/orm/lib/Doctrine/ORM/Mapping/MappingException.php:752

**Comment by kokspflanze** [comment]
hi =)

i removed the dependency and added a little readme.

the only problem is atm the annotation in the entity with the reference to the user maybe you have an  good idear.
